name: webapp-ci
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Set up JDK
        uses: action/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build with maven
        run: mvn clean

